name: mcban
version: "1.0"
main: mcban\Main
api:
- 2.0.0
- 1.13.0
- 1.12.0
author: v0xii
commands:
    mcban:
        description: "ban"
        usage: "/mcban <nick> <powod>"
        permission: mcban.command
permissions:
 mcban.command:
  description: "ban"
  default: op