# Config file for TimeCommander by LDX;

# List of commands for the plugin to execute at the given times;
# Command: Command to execute;
# Time: Amount of time in minutes between command executions;
Commands:
  - Command: weather world clear
    Time: 1
  - Command: reload
    Time: 60
  - Command: time set 0
    Time: 5
