name: CoreLexon
main: Gracz\Main
api:
- 1.13.1
- 2.0.0
version: 1.0.5
author: Lexon
commands: 
    gracz:
       description: "Pozwala sprawdzic swoje statystyki!"
       aliases: [player]
    regulamin:
       description: "Pozwala sprawdzic swoje statystyki!"
       aliases: [rules]
    plugins:
       description: "Pozwala sprawdzic swoje statystyki!"
       aliases: [pl]
    premiumcase:
       description: "Dodaje pierozki!"
       aliases: [pcase]
    pomoc:
       description: "Dodaje pierozki!"
       aliases: [help]
    klucz:
       description: "Dodaje pierozki!"
       aliases: [key]
    stoniarka:
       description: "Dodaje pierozki!"
       aliases: [stowniarka]
    cobblex:
       description: "Dodaje pierozki!"
       aliases: [cx]
    pall:
       description: "Dodaje pandory"
       aliases: [premiumcasall]
    vip:
       description: "Informacje o randze VIP"
       aliases: [vip]
    svip:
       description: "Informacje o randze Svip"
       aliases: [svip]
    rzucane:
       description: "Dodaje rzucane tnt"
       aliases: [rzucane]
    cobblestone:
       description: "Uzyj /cobblestone off/on aby wylaczyc lub wlaczyc drop cobblestona"
       aliases: [cobble]
    ip:
       description: "Uzyj /ip"
       aliases: [itempickup]
    ts3:
       description: "Komenda na sprawdzenie /ts3"
       aliases: [ts]
    yt:
       description: "Komenda na sprawdzenie /yt"
       aliases: [youtube]
