# The period of time that a player cannot logout for after damaging/getting damaged by another player
interval: 16
# Blocked commands
blocked-commands:
    - /spawn
    - /tp
    - /tpa
    - /back
    - /g
    - /schowek
    - /schowek wyplac
    - /schowek wyplac koxy
    - /schowek wyplac refy
    - /schowek wyplac perly
    - /schowek wyplac koxy 10
    - /schowek wyplac refy 10
    - /schowek wyplac perly 10
    - /SPAWN
    - /TPA
    - /back
    - /G DOM
    - /g dom
    - /g baza
    - /f home
    - /f dom
    - /g home
    - /arena
    - /ARENA
    - /LOSOWE
    - /losowe
    - /WYSPA TP
    - /wyspa tp
    - /tpahere
    - /TPAHERE
    - /TPACCEPT
    - /tpaccept
    - /HOME
    - /home
    - /TPYES
    - /tpyes