---
# Os usuários são capazes de obter apenas um kit por vida
one-kit-per-life: true

# Os usuários são capazes de obter um kit se eles sair do jogo e se eles não morrerem (só funciona se um kit-por-vida: true)
reset-on-logout: true

# Uso construído em sistema de permissão mesmo se usando PurePerms
force-builtin-permissions: false

# Texto da Placa (Capitais não importam)
sign-text: "[AdvancedKits]"
...