---
page_1:
  message_1: §b• Komendy serwera <1/3> •
  message_2: §b• /g pomoc <1/3> - Komendy gildii •
  message_3: §b• /statystyki - twoje staty •
  message_4: §b• /stoniarka - kupno stoniarki •
  message_5: §b• /exp - kupno expa •
  message_6: §b• /fireaspect - kupno podpalania •
  message_7: §b• /rangi - informacje o rangach •
  message_8: §b• /piorun - kupno specjalnej kości •
  message_9: §b• /losowe - teleportacja w losose miejsce •
  message_10: §b• Kolejna strona komend - /help 2 •
page_2:
  message_1: §b• Komendy serwera <2/3> •
  message_2: §b• /msg <nick> wiadomość - prywatna wiadomość •
  message_3: §b• /kit - Lista dostępnych kitów •
  message_4: §b• /kit gracz - startowe itemy •
  message_5: §b• /tpa <nick> - prośba o teleportacje •
  message_6: §b• /tpaccept - akceptuje prośbę o teleportacje •
  message_7: §b• /tpdeny - odrzuca prośbę o teleportacje •
  message_8: §b• /tpahere - prośba o teleportacje do nas •
  message_9: §b• /spawn - teleportacja na spawn •
  message_10: §b• Kolejna strona komend - /help 3 •
page_3:
  message_1: §b• Komendy serwera <3/3> •
  message_2: §b• /pay <nick> ilość - przesyłanie pieniędzy •
  message_3: §b• /seemoney <nick> - ilość monet danej osoby •
  message_4: §b• /warp - Lista warpow •
  message_5: §b• /sethome <nazwa> - ustawianie home •
  message_6: §b• /home <nazwa> - teleportacja do home •
  message_7: §b• Zauważyłeś/aś tutaj brak ważnej komendy? •
  message_8: §b• Napisz do właściciela serwera •
  message_9: §b• Jeżeli nadal nie znasz jakiejś komendy pisz •
  message_10: §b• do administracji naszego serwera •
page_4:
  message_1: first message here
  message_2: second message here
  message_3: third message here
  message_4: fourth message here
  message_5: fifth message here
  message_6: sixth message here
  message_7: seventh message here
  message_8: eighth message here
  message_9: ninth message here
  message_10: tenth message
page_5:
  message_1: first message here
  message_2: second message here
  message_3: third message here
  message_4: fourth message here
  message_5: fifth message here
  message_6: sixth message here
  message_7: seventh message here
  message_8: eighth message here
  message_9: ninth message here
  message_10: tenth message
page_6:
  message_1: first message here
  message_2: second message here
  message_3: third message here
  message_4: fourth message here
  message_5: fifth message here
  message_6: sixth message here
  message_7: seventh message here
  message_8: eighth message here
  message_9: ninth message here
  message_10: tenth message
page_7:
  message_1: first message here
  message_2: second message here
  message_3: third message here
  message_4: fourth message here
  message_5: fifth message here
  message_6: sixth message here
  message_7: seventh message here
  message_8: eighth message here
  message_9: ninth message here
  message_10: tenth message
page_8:
  message_1: first message here
  message_2: second message here
  message_3: third message here
  message_4: fourth message here
  message_5: fifth message here
  message_6: sixth message here
  message_7: seventh message here
  message_8: eighth message here
  message_9: ninth message here
  message_10: tenth message
page_9:
  message_1: first message here
  message_2: second message here
  message_3: third message here
  message_4: fourth message here
  message_5: fifth message here
  message_6: sixth message here
  message_7: seventh message here
  message_8: eighth message here
  message_9: ninth message here
  message_10: tenth message
page_10:
  message_1: first message here
  message_2: second message here
  message_3: third message here
  message_4: fourth message here
  message_5: fifth message here
  message_6: sixth message here
  message_7: seventh message here
  message_8: eighth message here
  message_9: ninth message here
  message_10: tenth message
...
