# The period of time that a player cannot logout for after damaging/getting damaged by another player
interval: 16
# Blocked commands
blocked-commands:
    - /spawn
    - /tp
    - /tpa
    - /SPAWN
    - /TPA
    - /G DOM
    - /g dom
    - /arena
    - /ARENA
    - /LOSOWE
    - /losowe
    - /WYSPA TP
    - /wyspa tp
    - /tpahere
    - /TPAHERE
    - /TPACCEPT
    - /tpaccept
    - /HOME
    - /home
    - /TPYES
    - /tpyes