---
name: FactionsPro
author: xExiiK
description: A Plugin For Easily Managing Factions
version: 1.4.1
main: FactionsPro\FactionMain
api: 3.0.0
commands:
  g:
    description: use /f help for all parameters
    permission: f.command  
permissions:
  f.command:
    default: true
    description: Allow use of all faction commands
  fac.override:
    default: op
    description: Allows op users to override factions 
...
