---
#time in seconds a player has to wait to send a message again
time: 10
#max warnings a player will receive until they receive a block type
max_warnings: 5
#warn player each time they spam
warning_message: "&6Nie spam!&7 %warns%"
#What type of block do you want?
#Types: message, mute, kick, ban, ban-ip
block_type: kick
#how much time should the player be muted (in seconds)
mute_time: 60
#message when player gets muted
mute_message: "&6Zostales zmutowany za spam!."
#message when player is still muted
muted_message: "&6Jestes zmutowany!."
un-muted_message: "&6Otrzymales UNMUTE!"
#Reason why player was kicked
#%player% = players name
kick_reason: "&6Zostales kick za spam."
#Reason why player was banned
#%player% = players name
ban_reason: "&6Zostales zbanowany za spam!"
#Reason why player was ip-banned
#%player% = players name
ip_ban_reason: ""
#message that will be sent if player is spamming
#%player% = players name
message: ""
...
