---
ctRandomTeleport:
  max-x: 1450
  max-z: 1450
infovip:
- §8• §7» §bUprawnienia §3★ §8•
- §8• §7* §b/spawn §8•
- §8• §7* §b/repair §8•
- §8• §7* §b/tpa §8•
- §8• §7* §b/kit §3Set Prot IV Unb III, Miecz Sharpness V FireAspect II, Miecz Sharpness
  V Knockback II §8•
- §8• §7* §3Kilof Efficiency V Fortune 3 Unb 3 §8•
- §8• §7* §32 koxy, 7 refili, 2 perly §8•
- §8• §7* §bWiekszy drop o 10% §8•
- §8• §7» §bRange mozesz kupic na §7is.funhard.pl §8•
- §8• §bKoszt §77.48zl §8•
infosvip:
- §8• §7» §bUprawnienia §3★ §8•
- §8• §7* §b/spawn §8•
- §8• §7* §b/repair §8•
- §8• §7* §b/tpa §8•
- §8• §7* §b/tpahere §8•
- §8• §7* §b/near §8•
- §8• §7* §b/back §8•
- §8• §7* §b/heal §8•
- §8• §7* §b/kit §3Set Prot IV Unb III, Miecz Sharpness V FireAspect II, Miecz Sharpness
  V Knockback II §8•
- §8• §7* §3Kilof Efficiency V Fortune 3 Unb 3 §8•
- §8• §7* §35 koxow, 11 refili, 5 perel §8•
- §8• §7* §bWiekszy drop o 30% §8•
- §8• §7» §bRange mozesz kupic na §7is.funhard.pl §8•
- §8• §bKoszt §711.07zl §8•
infocobblex:
- §8• §7* §bCobbleX §7to unikalny blok z ktorego wypadaja losowe itemy §8•
- §8• §7* §7Takie jak §b§l↓
- §8• §7* §3sztabka zelaza, diament, szmaragd, sztabka zlota, perla, jasnoglaz §8•
- §8• §7* §3jablko, biblioteczka, quartz, sadzonka, siarka, skora §8•
- §8• §7* §bCobbleX §7kupuje sie za 9 x 64 cobblestone §8•
- §8• §7* §7Aby zakupic wpisz §b/cobblex kup §8•
infostoniarka:
- §8• §7Co to §bStoniarka?
- §8• §7* §3Jest to blok ktory po postawieniu tworzy §8•
- §8• §7* §3nad soba stone §8•
- §8• §7Aby kupic wpisz §b§l↓ §8•
- §8• §7* §b/stoniarka kup - §7Koszt §b2 diamenty §8•
infoobsydianiarka:
- §8• §7Co to §bObsydianiarka?
- §8• §7* §3Jest to blok ktory po postawieniu tworzy §8•
- §8• §7* §3nad soba obsydian §8•
- §8• §7Aby kupic wpisz §b§l↓ §8•
- §8• §7* §b/obsydianiarka kup - §7Koszt §b2 diamenty §8•
infoyt:
- §8• §7Wymagania na range §b§l↓ §8•
- §8•  §3Minimum §b300 §3subow kanalu §8•
- §8•  §3Nagranie filmu z naszego serwera, lub trailer §8•
- §8•  §3Wyswietlenia i brak pustych subow §8•
- §8• §bSprawdz uprawnienia rangi pod /youtuber §8•
- §8• §3Aby otrzymac range wpisz §b/youtuber prosze (kanal)§3!§8•
infoyoutuber:
- §8• &7» &6Uprawnienia §3§l↓ §8•
- §8• §7* §b/spawn §8•
- §8• §7* §b/repair §8•
- §8• §7* §b/tpa §8•
- §8• §7* §b/tpahere §8•
- §8• §7* §b/near §8•
- §8• §7* §b/back §8•
- §8• §7* §b/heal §8•
- §8• §7* §b/kit svip §8•
- §8• §7* §bWiekszy drop o 30%  §8•
- §8• §3Aby otrzymac range wpisz §b/youtuber prosze (kanal)§3!§8•
infots3:
- §8• §8--------» §bTS3 §b«--------» §8•
- §8• » §7Nasz TeamSpeak - §3ohcode.pl §8•
- §8• §b«--------» §bTS3 §b§b«--------» §8•
infowww:
- §8• §b«--------» §bWWW §b«--------» §8•
- §8• » §7Nasza strona WWW - §3is.funhard.pl §8•
- §8• §b«--------» §bWWW §b«--------» §8•
infopomoc:
- §8•  §b§8---------§b Pomocnicze komendy §8---------§b  §8•
- §8• §b/g §8- §7Informacje dotyczace gildii §8•
- §8• §b/vip §8- §7Informacje dotyczace rangi VIP §8•
- §8• §b/svip §8- §7Informacje dotyczace rangi SVIP §8•
- §8• §b/tpa §8- §7Teleportacja do gracza §8•
- §8• §b/stoniarka §8- §7kupowanie stoniarki §8•
- §8• §b/cobblex §8- §7kupowanie cobblex §8•
- §8• §b/obsydianiarka §8- §7kupowanie obsydianiarka §8•
- §8• §b/yt §8- §7Informacje dotyczace rangi youtuber §8•
- §8• §b/sms §8- §7Wszystkie uslugi premium §8•
- §8• §b/msgoff §8- §7Wylancza /msg do ciebie §8•
- §8• §b/tpaoff §8- §7Wylancza /tpa do ciebie §8•
- §8• §b/boyfarmer §8- §7Informacje dotyczace §3BoyFarmera §8•
- §8• §b/sandfarmer §8- §7Informacje dotyczace §3SandFarmera §8•
- §8• §b/resetujranking §8- §7Resetuje twoj ranking! §8•
- §8•  §8---------§b §bPomocnicze komendy §8---------§b  §8•
infosms:
- §8•  §8---------§b Sklep SMS §8---------§b  §8•
- §8• §bVIP §8- §7Ranga vip posiadajaca wiele fajnych rzeczy! wiecej pod §b/vip §8•
- §8• §bSVIP §8- §7Ranga supervip posiadajaca wiele fajnych oraz ciekawych rzeczy! wiecej
  pod §b/svip §8•
- §8• §bMagiczna skrzynia §8- §7Otrzymujesz pierozek z ktorego dropia ciekawe itemki!
  §8•
- §8• §bUnban §8- §7Otrzymujesz unbana na serwerze §8•
- §8•  §8---------§b Sklep SMS §8---------§b  §8•
setgm1:
- §8• §bZmieniles swoj tryb na §3KREATYWNY §8•
setgm0:
- §8• §bZmieniles swoj tryb na §3SURVIVAL §8•
setgm2:
- §8• §bZmieniles swoj tryb na §3PRZYGODA §8•
setgm3:
- §8• §bZmieniles swoj tryb na §3OBSERWATOR §8•
tntpoziom:
- §f• §aTNT od Y 45! §8•
diaxoff:
- §f• Diamentowe itemy mozesz craftowac o godzinie 18;00 w poniedzialek! §8•
losowe:
- §f• §7Teleportowanie w losowe miejsce.. §f•
damage: 5
border-radius: 1500
msg:
  reached-end: '§8• §3Border: §bDotarles do granicy mapy!'
  out-of-bounds: '§8• §3Border: §bBlad!'
  out-of-reach: '§8• §3Border: §bNie mozesz stawiac blokow za granica mapy!'
posiadaszrangevouchervip:
- §8• §7Posiadasz juz range §bVIP§7! §8•
aktywacjarangavouchervip:
- §8• §7Zaaktywowano range §bVIP §7na twoim koncie! §8•
waznoscrangavouchervip:
- §8• §7Wazonosc twojej rangi §bVIP §7trwa do §bkonca edycji§7! §8•
youtuberprosbagracz:
- §8• §7Proprosiles o range §bYouTuber§7! §8•
- §8• §7Poczekaj na zatwierdzenie §badministratora! §8•
osiaglimitkox:
- §f• §7Osiagnales limit koxow! Nadmiar zostanie przeniesiony do schowka. §f•
osiaglimitref:
- §f• §7Osiagnales limit refili! Nadmiar zostanie przeniesiony do schowka. §f•
osiaglimitper:
- §f• §7Osiagnales limit perly! Nadmiar zostanie przeniesiony do schowka. §f•
hearts-per-kill: "10"
id1: 322
id1-name: §8[§eRefil§8]
id1-eff1: 1
id1-eff1-dur: 8
id1-eff1-amp: 1
id1-eff2: 10
id1-eff2-dur: 5
id1-eff2-amp: 2
id1-eff3: 12
id1-eff3-dur: 20
id1-eff3-amp: 1
id2: 466
id2-name: §8[§6Kox§8]
id2-eff1: 1
id2-eff1-dur: 8
id2-eff1-amp: 2
id2-eff2: 10
id2-eff2-dur: 15
id2-eff2-amp: 2
id2-eff3: 12
id2-eff3-dur: 60
id2-eff3-amp: 1
kb-modifier: true
kb-number: 0.200000
Min_Player: 91
Max_Player: 200
time: 10
max_warnings: 5
warning_message: "&6Nie spam!§3 %warns%"
block_type: message
mute_time: 60
mute_message: "&4Zostales zmutowany za spam!."
muted_message: "&4Jestes zmutowany!."
un-muted_message: "&4Otrzymales UNMUTE!"
kick_reason: "&aZostales kick za spam."
ban_reason: "&aZostales zbanowany za spam!"
ip_ban_reason: ""
message: "§4NIE SPAM!"
...