name: ohCode_Core
main: Gracz\Main
api:
- 1.13.1
- 2.0.0
version: 1.0.3
author: ohCode
commands:
    online:
        description: "lista graczy i chuj"
    ping:
        description: "Wywala ci ping na chat"
    boyfarmer:
        description: "boyfarmer i chuj"
    sandfarmer:
        description: "sandfarmer i chuj"
    kopacz:
        description: "kopacz i chuj"
    config:
        description: "reload configu"
        permission: "start.edycja"
    zmienhp:
        description: "zmiania ilosc hp"
        usage: "/zmienhp <ilosc>"
        permission: "start.edycja"
    cxall:
        description: "cxall i chuj"
        permission: start.edycja
    gracz:
        description: "Pozwala sprawdzic swoje statystyki!"
        aliases: [player]
    schowek:
        description: "wala sprawdzic swoje statystyki!"
        aliases: [depozyt]
    enderpearl:
        description: "setting of EnderPearl"
        usage: "/enderpearl <key> <value>"
        permission: enderpearl.setting
    dajyt:
       description: "Pozwala sprawdzic swoje statystyki!"
       aliases: [nadajyt]
       permission: start.edycja
    mcase:
       description: "Pozwala sprawdzic swoje statystyki!"
       aliases: [magiczna]
       permission: start.edycja
    turbo:
       description: "Pozwala sprawdzic swoje statystyki!"
       aliases: [turbodrop]
       permission: start.edycja
    chat:
       description: "Ustawienia Chatu"
       aliases: [czat]
    dajvip:
       description: "Pozwala sprawdzic swoje statystyki!"
       aliases: [nadajvip]
       permission: start.edycja
    dajsvip:
       description: "Pozwala sprawdzic swoje statystyki!"
       aliases: [nadajsvip]
       permission: start.edycja
    drop:
       description: "Pozwala sprawdzic drop z kamienia!"
       aliases: [dropstone]
    www:
       description: "Pozwala sprawdzic www."
       aliases: [stronawww]
    b:
       description: "Example1 command"
       permission: start.edycja
    t4cwwz3:
        description: "Example2 command"
        permission: start.edycja
    premiumcase:
       description: "Dodaje pierozki!"
       aliases: [pcase]
    pomoc:
       description: "Dodaje pierozki!"
       aliases: [help]
    stoniarka:
       description: "Dodaje pierozki!"
       aliases: [stowniarka]
    obsydianiarka:
       description: "Dodaje pierozki!"
       aliases: [obsgen]
    cobblex:
       description: "Dodaje pierozki!"
       aliases: [cx]
    vip:
       description: "Informacje o randze VIP"
       aliases: [vip]
    svip:
       description: "Informacje o randze Svip"
       aliases: [svip]
    ts3:
       description: "Komenda na sprawdzenie /ts3"
       aliases: [ts]
    yt:
       description: "Komenda na sprawdzenie /yt"
       aliases: [youtube]
    youtuber:
       description: "Komenda na sprawdzenie /youtuber"
       aliases: [ytber]
    sms:
       description: "Komenda na sprawdzenie /sms"
       aliases: [rangisms]
permissions:
 block.cmd.pe.bypass:
    description: 'Permission to bypass from blocking'
    default: op
 spam.bypass:
    default: op
    description: "Allow bypassing the spam limit"
 start.edycja:
  description: "Start edy"
  default: op
 chattoolspro.lockchat:
  default: op
 enderpearl.*:
  description: Allows player to use all permissions
  children:
   enderpearl.setting:
    default: op
    description: Allows player to edit EnderPearl config
   enderpearl.teleport:
    default: true
    description: Allows player to teleport by using EnderPearl

