---
#time in seconds a player has to wait to send a message again
time: 10
#max warnings a player will receive until they receive a block type
max_warnings: 3
#warn player each time they spam
warning_message: "&7Piszesz za szybko! &7Ostrzeżenia:&c %warns%&7/&c3"
#What type of block do you want?
#Types: message, mute, kick, ban, ban-ip
block_type: mute
#how much time should the player be muted (in seconds)
mute_time: 60
#message when player gets muted
mute_message: "&cZostałeś/aś wyciszony/a za zbyt szybkie pisanie."
#message when player is still muted
muted_message: "&eJestes wyciszony."
un-muted_message: "&aZostałeś/aś wyciszony/a! &bPisz wolniej bo zostaniesz wyciszony/a ponownie"
#Reason why player was kicked
#%player% = players name
kick_reason: "&cYou have been kicked for spamming."
#Reason why player was banned
#%player% = players name
ban_reason: "&4You have been banned for spamming!"
#Reason why player was ip-banned
#%player% = players name
ip_ban_reason: "&4You have been ip banned for spamming!"
#message that will be sent if player is spamming
#%player% = players name
message: "&aPlease let others chat, thank you. :)"
...
