---
Gracz: ~
groups:
  wlasciciel:
    default-nametag: '§6[{faction}] §cWlasciciel §7{display_name}'
    default-chat: §8• §3[{faction}] §8(§cWłaściciel§8)§7 {display_name} §9>>> §c{message} §8•'
  vip:
    default-nametag: '§6[{faction}] §bVIP §7{display_name}'
    default-chat: §8• §3[{faction}] §8[§bVIP§8]§7 {display_name} §9>>> §b{message} §8•'
  svip:
    default-nametag: '§6[{faction}] §6SVIP §7{display_name}'
    default-chat: §8• §3[{faction}] §8(§6SVIP§8)§7 {display_name} §9>>>§6 {message} §8•'
  yt:
    default-nametag: '§6[{faction}] §fYou§cTube §7{display_name}'
    default-chat: §8• §3[{faction}] §8(§fYou§cTube§8)§7 {display_name} §9>>> §f{message} §8•'
  helper:
    default-nametag: '§6[{faction}] §cHelper §7{display_name}'
    default-chat: §8• §3[{faction}] §8(§cHelper§8)§7 {display_name} §9>>> §c{message} §8•'
  pomocnik:
    default-nametag: '§6[{faction}] §cPomocnik §7{display_name}'
    default-chat: §8• §3[{faction}] §8(§cPomocnik§8)§7 {display_name} §9>>>§c {message} §8•'
  moderator:
    default-nametag: '§6[{faction}] §cModerator §7{display_name}'
    default-chat: §8• §3[{faction}] §8(§cModerator§8)§7 {display_name} §9>>>§c {message} §8•'
  admin:
    default-nametag: '§6[{faction}] §cAdmin §7{display_name}'
    default-chat: §8• §3[{faction}] §8(§cAdmin§8)§7 {display_name} §9>>>§c {message} §8•'
  gracz:
    default-nametag: '§6[{faction}] §7Gracz §7{display_name}'
    default-chat: §8• §3[{faction}] §8(§fGracz§8)§7 {display_name} §9>>> §f{message} §8•'
  sponsor:
    default-nametag: '§6[{faction}] §aSponsor §7{display_name}'
    default-chat: '§8• §3[{faction}] §8(§aSponsor§8)§7 {display_name} §9>>> §a{message} §8•'
custom-no-fac-message: ""
...
