---
enable-multiworld-support: false
custom-no-fac-message: '§'
groups:
  gracz:
    default-chat: '§8• §8[§7{pkt}§8] §2{faction} §7{display_name}: {message} §8•'
    default-nametag: '§8[§7{pkt}§8] §2{faction} §7{display_name}'
  vw:
    default-chat: '§8• §8[§7{pkt}§8] §2{faction} §8[§4vW§8] §7{display_name}: §4{message} §8•'
    default-nametag: '§8[§7{pkt}§8] §2{faction} §7{display_name}'
  vip:
    default-chat: '§8• §8[§7{pkt}§8] §2{faction} §eVIP §6{display_name}: {message} §8•'
    default-nametag: '§8[§7{pkt}§8] §2{faction} §eVIP §7{display_name}'
  wlasciciel:
    default-chat: '§8• §8[§7{pkt}§8] §2{faction} §8[§4W§8] §7{display_name}: §4{message} §8•'
    default-nametag: '§8[§7{pkt}§8] §2{faction} §7{display_name}'
  helper:
    default-chat: '§8• §8[§7{pkt}§8] §2{faction} §8[§3H§8] §7{display_name}: §3{message} §8•'
    default-nametag: '§8[§7{pkt}§8] §2{faction} §7{display_name}'
  moderator:
    default-chat: '§8• §8[§7{pkt}§8] §2{faction} §8[§aM§8] §7{display_name}: §a{message} §8•'
    default-nametag: '§8[§7{pkt}§8] §2{faction} §7{display_name}'
  administrator:
    default-chat: '§8• §8[§7{pkt}§8] §2{faction} §8[§cA§8] §7{display_name}: §c{message} §8•'
    default-nametag: '§8[§7{pkt}§8] §2{faction} §7{display_name}'
...
