---
enable-multiworld-support: false
custom-no-fac-message: ''
groups:
  Gracz:
    default-chat: '• [[{faction}]]{COLOR_WHITE} [Gracz] {display_name}: {message} •' 
    default-nametag: '{COLOR_GOLD}[{faction}]{COLOR_WHITE} [Gracz]{COLOR_WHITE} {display_name}'
    worlds: []
  Wlasciciell:
    default-chat: '{COLOR_RED}• [Właściciel] {display_name}{COLOR_RED}: {message} •' 
    default-nametag: '{COLOR_GOLD}[{faction}]{COLOR_WHITE} [Wlasciciel] {display_name}'
    worlds: []
  VIP:
    default-chat: '{COLOR_AQUA}• [[{faction}]] [VIP] {display_name}: {message} •' 
    default-nametag: '{COLOR_GOLD}[{faction}]{COLOR_WHITE} [VIP] {display_name}' 
    worlds: []
  Moderator:
    default-chat: '{COLOR_GREEN}• [[{faction}]] [Moderator] {display_name}: {message} •'
    default-nametag: '{COLOR_GOLD}[{faction}]{COLOR_WHITE} [Moderator] {display_name}' 
    worlds: []
  SVIP:
    default-chat: '{COLOR_YELLOW}• [[{faction}]] [{COLOR_YELLOW}S{COLOR_YELLOW}VIP{COLOR_YELLOW}] {display_name}: {message} •' 
    default-nametag: '{COLOR_GOLD}[{faction}]{COLOR_WHITE} [SVIP] {display_name}'
    worlds: []
  sponsor:
    default-chat: '{COLOR_GOLD}• [[{faction}]] [S{COLOR_GOLD}ponsor{COLOR_GOLD}] {display_name}: {message} •' 
    default-nametag: '{COLOR_GOLD}[{faction}]{COLOR_WHITE} [Sponsor]{COLOR_WHITE} {display_name}'
    worlds: []
  yt:
    default-chat: '{COLOR_WHITE}• [[{faction}]] [{COLOR_RED}You{COLOR_WHITE}Tube] {display_name}{COLOR_WHITE}: {message} •' 
    default-nametag: '{COLOR_ORANGE}[{faction}] [{COLOR_WHITE}You{COLOR_WHITE}Tube] {display_name}'
    worlds: []
  pomocnik:
    default-chat: '{COLOR_DARK_GREEN}• {COLOR_DARK_GREEN}[[{faction}]] {COLOR_DARK_GREEN}[Pomocnik] {display_name}: {message} •' 
    default-nametag: '{COLOR_GOLD}[{faction}] {COLOR_WHITE}[Pomocnik]{COLOR_WHITE} {display_name}'
    worlds: []
  Admin:
    default-chat: '{COLOR_AQUA}§9• [[{faction}]] [Admin] {display_name}: {message} •' 
    default-nametag: '{COLOR_GOLD}[{faction}] {COLOR_WHITE}[Admin]{COLOR_WHITE} {display_name}'
    worlds: []
  Wlasciciel:
    default-chat: '{COLOR_RED}• [[{faction}]] [Właściciel] {display_name}{COLOR_RED}: {message} •' 
    default-nametag: '{COLOR_GOLD}[{faction}]{COLOR_WHITE} [Wlasciciel] {display_name}'
    worlds: []
...