---
enable-multiworld-support: false
custom-no-fac-message: §
groups:
  gracz:
    default-chat: '§8• §f{pkt} §2{faction} §7{display_name}§8» §f{message}
      §8•'
    default-nametag: §f{pkt} §2{faction} §7{display_name}
  vip:
    default-chat: §8• §f{pkt} §2{faction} §eVIP §7{display_name}§8»§f
      {message} §8•
    default-nametag: §f{pkt} §2{faction} §eVIP §7{display_name}
  wlasciciel:
    default-chat: '§8• §f{pkt} §2{faction} §4W §7{display_name}§8»
      §6{message} §8•'
    default-nametag: §f{pkt} §2{faction} §4W §7{display_name}
  ohcode:
    default-chat: '§8• §8[§4§lohCode.pl§8] §7{display_name}§8»
      §6{message} §8•'
    default-nametag: §8[§4§lohCode.pl§8] §7{display_name}
  helper:
    default-chat: '§8• §f{pkt} §2{faction} §9H §7{display_name}§8:
      §7{message} §8•'
    default-nametag: §f{pkt} §2{faction} §9H §7{display_name}
  moderator:
    default-chat: '§8• §f{pkt} §2{faction} §2M §7{display_name}§8»
      §7{message} §8•'
    default-nametag: §f{pkt} §2{faction} §2M §7{display_name}
  administrator:
    default-chat: '§8• §f{pkt} §2{faction} §cA §7{display_name}§8»
      §7{message} §8•'
    default-nametag: §f{pkt} §2{faction} §cA §7{display_name}
  yt:
    default-chat: '§8• §f{pkt} §2{faction} §fY§4T §7{display_name}§8»
      §f{message} §8•'
    default-nametag: §f{pkt} §2{faction} §fY§4T §7§7{display_name}
  svip:
    default-chat: '§8• §f{pkt} §2{faction} §6SVIP §7{display_name}§8»
      §7{message} §8•'
    default-nametag: §f{pkt} §2{faction} §6SVIP §7{display_name}
...
