---
messages:
- fuck
- craftture
- maxc
- port
- elitepe
- "26"
- "19132"
- craft
- ture
- craftture
- leet
- cc
- Blenderman
- playmc
- kurwa
- chuj
- huj
- pe
- "21658"
identify-capital-alphabet: false
mosaic: '*'
...
