#KillMoney v0.1 Config File
#
#Economy Plugin. Options: PocketMoney, Economy
Economy-Plugin: Economy
#
#Money to Killer
Money: 50
#
#Message to Killer
Message: "§a> §b[HardPe]§a dostałeś $@monet za zabicie @player! <"
